### ISSUE TITLE
Standardize the outputs (for easy user data manipulation)

### ISSUE THREAD

**Issue by dxcore35** [g-battaglia/kerykeion#3]
# WHAT
- the current data display is not standardized across the outputs
- keep the full name not abbreviation (use can cut it by himself)
- keep the angles in brackets
- the data header, user name, separator name is not needed (user can add this by himself if it is needed)

# WHY

Easy manipulation of data, customization of output. 

# HOW

## VARIATION 1: Plain data

~~-------------------DON'T PRINT THIS LINE ------------------------------~~
~~NAME: Kanye~~

**PLANETS**

~~<sub>[Planet | Zodiac | House | Angle]</sub>~~ not printed only in documentation
Sun:     Gemini     12  (17.599)|
Moon:  Pisces     9  (16.425)
Mercury:  Taurus   11 (26.286)

**HOUSES**

~~<sub>[House | Zodiac | Angle]</sub>~~ not printed only in documentation
1:     Cancer  (17.996)
2:     Leo  (9.506)
3:     Virgin  (4.022)

## VARIATION 2: Alternative option to print output as markdown

~~-------------------DON'T PRINT THIS LINE ------------------------------~~
~~NAME: Kanye~~

### PLANETS

|Planet | Zodiac | House | Angle|
|---|---|---|---|
Sun |     Gemini |     12 | (17.599)|
Moon |  Pisces |     9  |(16.425)|
Mercury | Taurus  |   11 | (26.286)|

### HOUSES

|House | Zodiac | Angle|
|---|---|---|
1 | Cancer | (17.996)
2 | Leo |  (9.506)
3 | Virgin | (4.022)

**Comment by dxcore35** [comment]
No comment about what was resolved / why it was closed. Nice.

**Comment by g-battaglia** [comment]
Sorry probably it went lost, I still have to get used to github. I closed it because I updated the project and now it's more clear in its purpose, it's an utility library so the output.py file is just an example of how it can be used! I probably should change it in oputput_exemple.py to be even clearer. I won't update it because of that, if you want to get the data you should use the object attributes like object.second_house and similar, I'll try to write the documentation. With that you can write simply your own output in the way you want.

**Comment by dxcore35** [comment]
Yea, you see I was thinking that this is tool and not a object library. The "oputput_exemple.py" will make the things more clear! Anyway great tool.
